import 'package:flutter_bloc/flutter_bloc.dart';
import '../../data/models/schedules_model.dart';
import '../../data/repositories/schedules_repository.dart';

part 'checklist_state.dart';

class ChecklistCubit extends Cubit<ChecklistState> {
  final ChecklistRepository repository;
  String? currentChildId;

  ChecklistCubit({required this.repository}) : super(ChecklistInitial());

  Future<void> loadChecklists(String childId) async {
    currentChildId = childId;
    emit(ChecklistLoading());
    try {
      final items = await repository.fetchChecklist(childId);
      emit(ChecklistLoaded(items));
    } catch (e) {
      emit(ChecklistError(e.toString()));
    }
  }

  Future<void> addItem(String title) async {
    if (currentChildId == null) return;
    
    try {
      final newItem = ChecklistItem(
        id: '', // Will be generated by Supabase
        childId: currentChildId!,
        title: title,
        done: false,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );
      await repository.addChecklistItem(newItem);
      await loadChecklists(currentChildId!);
    } catch (e) {
      emit(ChecklistError(e.toString()));
    }
  }

  Future<void> toggleItem(ChecklistItem item) async {
    try {
      final updated = item.copyWith(
        done: !item.done,
        updatedAt: DateTime.now(),
      );
      await repository.updateChecklistItem(updated);
      if (currentChildId != null) {
        await loadChecklists(currentChildId!);
      }
    } catch (e) {
      emit(ChecklistError(e.toString()));
    }
  }

  Future<void> deleteItem(String id) async {
    try {
      await repository.deleteChecklistItem(id);
      if (currentChildId != null) {
        await loadChecklists(currentChildId!);
      }
    } catch (e) {
      emit(ChecklistError(e.toString()));
    }
  }
}
