// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlkGkhfzCjAX0nMQQqpKNNBMEWb1e7Fpg',
    appId: '1:615972119406:web:e066a37f25b44667dd577f',
    messagingSenderId: '615972119406',
    projectId: 'tifly-ae48f',
    authDomain: 'tifly-ae48f.firebaseapp.com',
    storageBucket: 'tifly-ae48f.firebasestorage.app',
    measurementId: 'G-F4V09WFGZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWjn2zM2s38tRixEti4FXiU1qkdJrD78',
    appId: '1:615972119406:android:fc2bc2e3a6b048a5dd577f',
    messagingSenderId: '615972119406',
    projectId: 'tifly-ae48f',
    storageBucket: 'tifly-ae48f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3VQujDMaKzVD696n7rtrkPkrHb4ftWO0',
    appId: '1:615972119406:ios:a307d58b0da8d4e5dd577f',
    messagingSenderId: '615972119406',
    projectId: 'tifly-ae48f',
    storageBucket: 'tifly-ae48f.firebasestorage.app',
    iosBundleId: 'com.example.tifli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3VQujDMaKzVD696n7rtrkPkrHb4ftWO0',
    appId: '1:615972119406:ios:a307d58b0da8d4e5dd577f',
    messagingSenderId: '615972119406',
    projectId: 'tifly-ae48f',
    storageBucket: 'tifly-ae48f.firebasestorage.app',
    iosBundleId: 'com.example.tifli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlkGkhfzCjAX0nMQQqpKNNBMEWb1e7Fpg',
    appId: '1:615972119406:web:727b1e20f2160364dd577f',
    messagingSenderId: '615972119406',
    projectId: 'tifly-ae48f',
    authDomain: 'tifly-ae48f.firebaseapp.com',
    storageBucket: 'tifly-ae48f.firebasestorage.app',
    measurementId: 'G-RQRL07SDVC',
  );
}
